language: java
jdk:
  - oraclejdk8
script: mvn -Dlogging.level.=WARN -Dlogging.level.root=WARN -Dlogging.level.org=WARN -Pcheck-checkstyle,check-cycles,check-pmd-cpd,check-findbugs,attach-integration-test verify
after_success:
  - mvn -Dlogging.level.=WARN -Dlogging.level.root=WARN -Dlogging.level.org=WARN -Pattach-integration-test cobertura:cobertura-integration-test org.eluder.coveralls:coveralls-maven-plugin:4.2.0:report
